import { Mulish } from "next/font/google";
import "./globals.css";
import { Abhaya_Libre } from 'next/font/google';


// Initialize the font with desired subsets and weights
const mulish = Mulish({
  subsets: ['latin'],
  // Specify the weights you need
  weight: ['300', '400', '500', '600', '700'],
  // Optional: specify font display
  display: 'swap',
  // Optional: specify variable font
  variable: '--font-mulish',
});

export const abhayaLibre = Abhaya_Libre({
  weight: '800', // ExtraBold weight
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-abhaya-libre',
});

export const metadata = {
  title: "Welcome to Find-a-Home FUTA ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
      <html lang="en">
        <body
          className={`${mulish.className}  antialiased`}
        >   
         {children}
        </body>
      </html>
  );
}
